### ISSUE TITLE
Error from example code

### ISSUE THREAD

**Issue by KomiGH** [GRealesM/RapidoPGS#9]
Hi,

thank you for this ultra fast package. using the single function of the package is very easy. But when I tried the multi function I got an error message already when I repeated your example run with your code:
![image](https://github.com/GRealesM/RapidoPGS/assets/105348259/22e25cfd-ecb3-4812-8f5c-597b29c37eb4)

Even the number of the snp-s after filtering are different from your run (first 99,996 variants matched and thenn 9,075 variantsmatched).
I can't find what could be a problem. For me it seems that when after filtering the number of snp-s are too low in a block sometimes there is no match in the LD matrix so susie got an empty data. Can the problem be the new block that you implemented in your last update? 
When I tried the function with my own data I got the same error but only during the the 6th chromosome.
Thank you for your help in advance

Best,
Peter Erdelyi

**Comment by GRealesM** [comment]
Hi Peter,

Thank you for raising this issue, and sorry for the delay -- I was on holiday. 
I discovered the problem: susieR (the package we need to compute PGS assuming multiple causal variants per block) changed recently and now requires the sample size. Hence, your error is due to this requirement not being met. 
Since this wasn't an issue in past versions, I need to update RápidoPGS (and the vignettes) to add this requirement, which I'll do in the next few days. In the meantime, I hope RápidoPGS single is still useful for your purposes.

Thanks for your patience and for making me aware of this problem.

Guillermo

**Comment by GRealesM** [comment]
Hi Peter. I've updated RápidoPGS to v2.3.0, where the problem you're facing should now be fixed.
I hope to get this new version to CRAN in the next few days, but you can use the GitHub version in the meantime.
Please let me know if you have further problems, and I'll do my best to fix them.

Best wishes,
Guillermo
